### ISSUE TITLE
UCF101 future prediction with resolution 128

### ISSUE THREAD

**Issue by SeminKim** [16lemoing/ccvs#4]
On Table D1 in the paper, it says 16-frame unconditional video synthesis on UCF-101 was done in resolution 128x128.
However, I found that released checkpoints are for 256x256 resolution instead of 128x128 - so the resolution does not match.
Could you release checkpoints and scripts for reproducing this table?

**Comment by 16lemoing** [comment]
Hi ! We follow the experimental protocol from MoCoGANHD [1] where video are synthesized at 256x256 and resized to 128x128 during evaluation for fair comparisons with prior works (see Section 4.3 of [1]: "We resize frames for all methods to 128x128 when calculating IS and FVD"). 

[1] A good image generator is what you need for high-resolution video synthesis, ICLR'21

**Comment by SeminKim** [comment]
Thank you for your prompt response!
